sudo: required
services:
  - docker

before_install:
  - docker build -t raydeng83/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run raydeng83/react-test npm test -- --coverage

after_success:
  - docker build -t raydeng83/multi-client ./client 
  - docker build -t raydeng83/multi-nginx ./nginx
  - docker build -t raydeng83/multi-server ./server
  - docker build -t raydeng83/multi-worker ./worker
  # Log in to the Docker Cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push raydeng83/multi-client
  - docker push raydeng83/multi-nginx
  - docker push raydeng83/multi-server
  - docker push raydeng83/multi-worker
